import{a as S,S as b,i}from"./assets/vendor-C4-ZuMk8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const v="46474433-011ac89f5ff1a7f52c1dd2f66",$="https://pixabay.com/api/";async function m(t,r=1,n=15){const s=`${$}?key=${v}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`;console.log("Fetching images with URL:",s);try{const e=await S.get(s);return console.log("Response received:",e),e.status!==200?(console.error("Non-200 response:",e),iziToast.error({title:"Error",message:"Failed to fetch images. Please try again."}),[]):e.data.hits}catch(e){throw console.error("Error fetching images:",e.response||e.message),new Error("Failed to fetch images.")}}const f=document.querySelector(".gallery");let g=null;function h(t){const r=new Set([...f.querySelectorAll(".photo-card")].map(s=>s.dataset.id)),n=t.filter(s=>!r.has(s.id.toString())).map(({id:s,webformatURL:e,largeImageURL:o,tags:a,likes:p,views:y,comments:w,downloads:L})=>`
          <div class="photo-card" data-id="${s}">  <!-- Assign data-id to track unique images -->
              <a href="${o}">
                  <img src="${e}" alt="${a}" loading="lazy" />
              </a>
              <div class="info">
                  <p><b>Likes</b>: ${p}</p>
                  <p><b>Views</b>: ${y}</p>
                  <p><b>Comments</b>: ${w}</p>
                  <p><b>Downloads</b>: ${L}</p>
              </div>
          </div>`).join("");f.insertAdjacentHTML("beforeend",n),g?g.refresh():g=new b(".gallery a")}function E(){f.innerHTML=""}const q=document.querySelector("#search-form"),P=document.querySelector('input[name="searchQuery"]'),d=document.querySelector(".loader"),c=document.querySelector(".load-more");let u=1,l="";q.addEventListener("submit",I);c.addEventListener("click",A);async function I(t){if(t.preventDefault(),l=P.value.trim(),!l){i.warning({title:"Warning",message:"Please enter a search query."});return}E(),d.classList.add("show"),c.classList.add("hidden"),u=1;try{const r=await m(l,u);if(console.log("Images fetched:",r),!r||r.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(r),r.length>=15&&c.classList.remove("hidden")}catch(r){console.error("Error in onSearch:",r.message),i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{d.classList.remove("show")}}async function A(){u+=1,d.classList.add("show");try{const t=await m(l,u);if(t.length===0){i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),c.classList.add("hidden");return}h(t),O(),t.length<15&&c.classList.add("hidden")}catch{i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{d.classList.remove("show")}}function O(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
